######################################################################
# Automatically generated by qmake (3.0) ?? 4? 7 13:57:03 2020
######################################################################
QT += widgets serialport

TEMPLATE = app
TARGET = fake_cutecom
INCLUDEPATH += .

# Input
HEADERS += ../controlpanel.h ../mainwindow.h
SOURCES += ../controlpanel.cpp ../main.cpp ../mainwindow.cpp
